zfs ./sig/i960/ctools.sig
zfs ./sig/h8/gnu.sig
zfs ./sig/h8/coff.sig
zfs ./sig/arm/pe.sig
zfs ./sig/arm/elf.sig
zfs ./sig/arm/android_arm.sig
zfs ./sig/arm/vc_atl.sig
zfs ./sig/arm/armlibl.sig
zfs ./sig/arm/vc_extra.sig
zfs ./sig/arm/mfc.sig
zfs ./sig/arm/armlibb.sig
zfs ./sig/arm/armlib_l.sig
zfs ./sig/arm/vc_rtf.sig
zfs ./sig/mc68/cwpalm.sig
zfs ./sig/tms320c6/tms320c6.sig
zfs ./sig/tms320c6/coff.sig
zfs ./sig/c166/keil.sig
zfs ./sig/ebc/pe.sig
zfs ./sig/mips/pe.sig
zfs ./sig/mips/mfc.sig
zfs ./sig/mips/psyq.sig
zfs ./sig/mips/psx.sig
zfs ./sig/sh3/pe.sig
zfs ./sig/sh3/mfc.sig
zfs ./sig/pc/dm_d2_win.sig
zfs ./sig/pc/pe.sig
zfs ./sig/pc/bc15owl.sig
zfs ./sig/pc/sm16rdos.sig
zfs ./sig/pc/bc31rtw.sig
zfs ./sig/pc/wa32stn.sig
zfs ./sig/pc/z316grfd.sig
zfs ./sig/pc/z316matw.sig
zfs ./sig/pc/mv16rdos.sig
zfs ./sig/pc/b532cgw.sig
zfs ./sig/pc/z316matd.sig
zfs ./sig/pc/msmfc64u.sig
zfs ./sig/pc/msddk32.sig
zfs ./sig/pc/tpdos.sig
zfs ./sig/pc/pe64.sig
zfs ./sig/pc/d5vcl.sig
zfs ./sig/pc/omvc60.sig
zfs ./sig/pc/ms16os2.sig
zfs ./sig/pc/vc64extra.sig
zfs ./sig/pc/vc64rtf.sig
zfs ./sig/pc/sm16rwin.sig
zfs ./sig/pc/vc64seh.sig
zfs ./sig/pc/lx.sig
zfs ./sig/pc/gcc32rtf.sig
zfs ./sig/pc/iclapp64.sig
zfs ./sig/pc/bh32cls.sig
zfs ./sig/pc/le.sig
zfs ./sig/pc/z316rdos.sig
zfs ./sig/pc/dm32rw32.sig
zfs ./sig/pc/vc32mfce.sig
zfs ./sig/pc/vcseh.sig
zfs ./sig/pc/wa32rtn.sig
zfs ./sig/pc/win64unx.sig
zfs ./sig/pc/vc64_14.sig
zfs ./sig/pc/b516cgw.sig
zfs ./sig/pc/bc31tvd.sig
zfs ./sig/pc/bds8cg32.sig
zfs ./sig/pc/ms64wdk.sig
zfs ./sig/pc/bds2006.sig
zfs ./sig/pc/mssdk32.sig
zfs ./sig/pc/dm16dos.sig
zfs ./sig/pc/ulink.sig
zfs ./sig/pc/iclapp.sig
zfs ./sig/pc/bc31cls.sig
zfs ./sig/pc/msfps40.sig
zfs ./sig/pc/mv16mfc.sig
zfs ./sig/pc/vcextra.sig
zfs ./sig/pc/exe.sig
zfs ./sig/pc/mv16grfd.sig
zfs ./sig/pc/wa16rtw.sig
zfs ./sig/pc/wa32qnx.sig
zfs ./sig/pc/wa16std.sig
zfs ./sig/pc/csetrto.sig
zfs ./sig/pc/c4vcl.sig
zfs ./sig/pc/vc432opg.sig
zfs ./sig/pc/libc.sig
zfs ./sig/pc/bh16cls.sig
zfs ./sig/pc/mv16rwin.sig
zfs ./sig/pc/vc32_14.sig
zfs ./sig/pc/vc32rtf.sig
zfs ./sig/pc/highrto.sig
zfs ./sig/pc/bds8ext.sig
zfs ./sig/pc/bh16dbe.sig
zfs ./sig/pc/bc15c2.sig
zfs ./sig/pc/wa16qnx.sig
zfs ./sig/pc/tptv.sig
zfs ./sig/pc/bh32owl.sig
zfs ./sig/pc/bdsboost.sig
zfs ./sig/pc/vireoms.sig
zfs ./sig/pc/wa16rtd.sig
zfs ./sig/pc/iclmat.sig
zfs ./sig/pc/msddk64.sig
zfs ./sig/pc/vc432cab.sig
zfs ./sig/pc/tpsig2n.sig
zfs ./sig/pc/b32vcl.sig
zfs ./sig/pc/win32unx.sig
zfs ./sig/pc/nlm.sig
zfs ./sig/pc/bh32dbe.sig
zfs ./sig/pc/wa32sto.sig
zfs ./sig/pc/msmfc2.sig
zfs ./sig/pc/vc32ucrt.sig
zfs ./sig/pc/wa32rt_.sig
zfs ./sig/pc/mccor.sig
zfs ./sig/pc/msmfc2d.sig
zfs ./sig/pc/wa16rt_.sig
zfs ./sig/pc/vc32mfc.sig
zfs ./sig/pc/csetadd.sig
zfs ./sig/pc/msmfc64.sig
zfs ./sig/pc/msmfc2u.sig
zfs ./sig/pc/d4vcl.sig
zfs ./sig/pc/vac35wc.sig
zfs ./sig/pc/vireobc.sig
zfs ./sig/pc/bh16rdos.sig
zfs ./sig/pc/bh16grfd.sig
zfs ./sig/pc/bdsext.sig
zfs ./sig/pc/optima.sig
zfs ./sig/pc/bc15bids.sig
zfs ./sig/pc/tpsig2.sig
zfs ./sig/pc/msmfc64d.sig
zfs ./sig/pc/d3vcl.sig
zfs ./sig/pc/sm32rw32.sig
zfs ./sig/pc/emx32add.sig
zfs ./sig/pc/tptvdpmi.sig
zfs ./sig/pc/og70.sig
zfs ./sig/pc/osc60.sig
zfs ./sig/pc/bds8rw32.sig
zfs ./sig/pc/wa32rtt.sig
zfs ./sig/pc/bds40.sig
zfs ./sig/pc/tpowl.sig
zfs ./sig/pc/iclmat64.sig
zfs ./sig/pc/z316rwin.sig
zfs ./sig/pc/tpwin.sig
zfs ./sig/pc/ndprtd.sig
zfs ./sig/pc/vc64atl.sig
zfs ./sig/pc/vc64mfc.sig
zfs ./sig/pc/bh16ocf.sig
zfs ./sig/pc/bds8vcl.sig
zfs ./sig/pc/bc31rtd.sig
zfs ./sig/pc/bds2007.sig
zfs ./sig/pc/bh32ocf.sig
zfs ./sig/pc/mq16rdos.sig
zfs ./sig/pc/aztec.sig
zfs ./sig/pc/vc64ucrt.sig
zfs ./sig/pc/bh16owl.sig
zfs ./sig/pc/bh32rw32.sig
zfs ./sig/pc/bds.sig
zfs ./sig/pc/ne.sig
zfs ./sig/pc/ms32wdk.sig
zfs ./sig/pc/latrtd.sig
zfs ./sig/pc/ctask.sig
zfs ./sig/pc/sm16strm.sig
zfs ./sig/pc/z116rdos.sig
zfs ./sig/pc/bcb5rt.sig
zfs ./sig/pc/otp60.sig
zfs ./sig/pc/mssdk64.sig
zfs ./sig/pc/bh16rwin.sig
zfs ./sig/pc/bc31owlw.sig
zfs ./sig/pc/ulink64.sig
zfs ./sig/pc/vc432tap.sig
zfs ./sig/pc/wa32rtd.sig
zfs ./sig/pc/wa16rto.sig
zfs ./sig/pc/vc8atl.sig
zfs ./sig/pc/delphi.sig
zfs ./sig/pc/bsdi_31.sig
zfs ./sig/pc/vc7atl.sig
zfs ./sig/pc/b5132mfc.sig
zfs ./sig/pc/emx32rto.sig
zfs ./sig/pc/wa32rto.sig
zfs ./sig/pc/tpdpmi.sig
zfs ./sig/pc/wa32rtw.sig
